### PR TITLE
Use the private key from master

### LINKED ISSUE #25: Private key not available
```
No private key available!

Error: No private key available!
    at Object.module.exports.getPrivateKey (/home/strider/strider/node_modules/strider-ssh-deploy/keys.js:21:21)
    at getConnectionOptions (/home/strider/strider/node_modules/strider-ssh-deploy/deploy.js:12:8)
    at Object.deploy (/home/strider/strider/node_modules/strider-ssh-deploy/deploy.js:39:7)
    at Object.runPlugin (/home/strider/strider/node_modules/strider-simple-runner/node_modules/strider-runner-core/lib/utils.js:26:25)
    at /home/strider/strider/node_modules/strider-simple-runner/node_modules/strider-runner-core/lib/job.js:293:15
    at /home/strider/strider/node_modules/strider-simple-runner/node_modules/strider-runner-core/node_modules/async/lib/async.js:551:21
    at /home/strider/strider/node_modules/strider-simple-runner/node_modules/strider-runner-core/node_modules/async/lib/async.js:227:13
    at iterate (/home/strider/strider/node_modules/strider-simple-runner/node_modules/strider-runner-core/node_modules/async/lib/async.js:134:13)
    at /home/strider/strider/node_modules/strider-simple-runner/node_modules/strider-runner-core/node_modules/async/lib/async.js:145:25
    at /home/strider/strider/node_modules/strider-simple-runner/node_modules/strider-runner-core/node_modules/async/lib/async.js:229:17
    at /home/strider/strider/node_modules/strider-simple-runner/node_modules/strider-runner-core/node_modules/async/lib/async.js:556:34
    at Object.runPlugin (/home/strider/strider/node_modules/strider-simple-runner/node_modules/strider-runner-core/lib/utils.js:24:30)
    at /home/strider/strider/node_modules/strider-simple-runner/node_modules/strider-runner-core/lib/job.js:293:15
    at /home/strider/strider/node_modules/strider-simple-runner/node_modules/strider-runner-core/node_modules/async/lib/async.js:551:21
    at /home/strider/strider/node_modules/strider-simple-runner/node_modules/strider-runner-core/node_modules/async/lib/async.js:227:13
    at iterate (/home/strider/strider/node_modules/strider-simple-runner/node_modules/strider-runner-core/node_modules/async/lib/async.js:134:13)
```

I'll probably look into this at home later.

### PR DESCRIPTION
**Pull request by oliversalzburg**
Fixes #25 

A new release would be nice after this, so that I can test this on our production system.

### CODE REVIEW

File: keys.js [hunk 1]
```diff
@@ -42,3 +43,11 @@ function findBranch(branches, name) {
     return branch;
   }(name, foundBranch, branches))
 }
+
+function getMasterPrivKey(branches) {
```
Comment (knownasilya) [inline keys.js]: forEach here as well
